/**
 * MOVES DATABASE
 * All move definitions with damage, effects, costs, etc.
 */

export const MOVES = {
  Ember: { type: 'Fire', damage: 12, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'burn', chance: 0.1, duration: 2, damage: 1 } },
  Flamethrower: { type: 'Fire', damage: 26, warmup: 3, cooldown: 4, stamina: 45, cost: 45, effect: { type: 'burn', chance: 0.2, duration: 4, damage: 2 } },
  FireBlast: { type: 'Fire', damage: 35, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'burn', chance: 0.4, duration: 5, damage: 3 } },
  WaterGun: { type: 'Water', damage: 12, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'debuff_speed', chance: 0.1, duration: 2 } },
  Surf: { type: 'Water', damage: 26, warmup: 3, cooldown: 4, stamina: 45, cost: 45, effect: { type: 'debuff_speed', chance: 0.15, duration: 2 } },
  HydroPump: { type: 'Water', damage: 35, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'soak', chance: 0.3, duration: 4 } },
  VineWhip: { type: 'Grass', damage: 14, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'debuff_speed', chance: 0.15, duration: 3 } },
  RazorLeaf: { type: 'Grass', damage: 26, warmup: 3, cooldown: 4, stamina: 45, cost: 45, effect: { type: 'high_crit' } },
  SolarBeam: { type: 'Grass', damage: 35, warmup: 6, cooldown: 5, stamina: 55, cost: 75, effect: { type: 'energize', chance: 0.25, duration: 3, staminaBoost: 5 } },
  PsyBeam: { type: 'Psychic', damage: 11, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'confuse', chance: 0.3, duration: 3 } },
  Psychic: { type: 'Psychic', damage: 25, warmup: 3, cooldown: 4, stamina: 45, cost: 45, effect: { type: 'confuse', chance: 0.5, duration: 4 } },
  PsychicBlast: { type: 'Psychic', damage: 34, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'confuse', chance: 0.7, duration: 5 } },
  ThunderShock: { type: 'Electric', damage: 11, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'paralyze', chance: 0.2, duration: 3 } },
  Thunderbolt: { type: 'Electric', damage: 26, warmup: 3, cooldown: 4, stamina: 45, cost: 45, effect: { type: 'paralyze', chance: 0.3, duration: 4 } },
  Thunder: { type: 'Electric', damage: 35, warmup: 5, cooldown: 6, stamina: 65, cost: 75, effect: { type: 'paralyze', chance: 0.5, duration: 5 } },
  LowKick: { type: 'Fighting', damage: 10, warmup: 0, cooldown: 2, stamina: 20, cost: 25, effect: { type: 'debuff_speed', chance: 0.2, duration: 2 } },
  KarateChop: { type: 'Fighting', damage: 12, warmup: 0, cooldown: 2, stamina: 25, cost: 30, effect: { type: 'high_crit' } },
  Submission: { type: 'Fighting', damage: 28, warmup: 3, cooldown: 4, stamina: 50, cost: 50, effect: { type: 'recoil', damagePercent: 0.1 } },
  BrickBreak: { type: 'Fighting', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 45, effect: { type: 'remove_hazards' } },
  CloseCombat: { type: 'Fighting', damage: 35, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'recoil', damagePercent: 0.15 } },
  Earthquake: { type: 'Fighting', damage: 32, warmup: 4, cooldown: 5, stamina: 52, cost: 62, effect: { type: 'debuff_speed', chance: 0.2, duration: 3 } },
  AuraSphere: { type: 'Fighting', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 50, effect: { type: 'buff_instinct', chance: 0.15, duration: 4 } },
  DrainPunch: { type: 'Fighting', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'drain', chance: 0.5, duration: 1, healPercent: 0.5 } },
  DynamicPunch: { type: 'Fighting', damage: 30, warmup: 4, cooldown: 5, stamina: 50, cost: 60, effect: { type: 'confuse', chance: 0.5, duration: 3 } },
  Tackle: { type: 'Normal', damage: 7, warmup: 1, cooldown: 2, stamina: 20, cost: 30, effect: null },
  BodySlam: { type: 'Normal', damage: 21, warmup: 2, cooldown: 3, stamina: 42, cost: 35, effect: { type: 'stun', chance: 0.2, duration: 2 } },
  HyperBeam: { type: 'Normal', damage: 38, warmup: 8, cooldown: 8, stamina: 65, cost: 80, effect: { type: 'exhaust', duration: 3 } },
  SacredFire: { type: 'Fire', damage: 38, warmup: 6, cooldown: 6, stamina: 85, cost: 80, effect: { type: 'burn', duration: 3, damage: 2 } },
  Psystrike: { type: 'Psychic', damage: 40, warmup: 7, cooldown: 7, stamina: 90, cost: 85, effect: { type: 'confuse', chance: 1.0, duration: 2 } },
  OriginPulse: { type: 'Water', damage: 39, warmup: 7, cooldown: 6, stamina: 90, cost: 85 },
  PrecipiceBlades: { type: 'Fire', damage: 41, warmup: 8, cooldown: 7, stamina: 95, cost: 88 },
  DragonAscent: { type: 'Grass', damage: 40, warmup: 7, cooldown: 7, stamina: 92, cost: 87 },
  RoarOfTime: { type: 'Fighting', damage: 42, warmup: 8, cooldown: 8, stamina: 100, cost: 90, effect: { type: 'exhaust', duration: 2 } },
  SpacialRend: { type: 'Water', damage: 40, warmup: 7, cooldown: 7, stamina: 92, cost: 87 },
  ShadowForce: { type: 'Psychic', damage: 38, warmup: 6, cooldown: 7, stamina: 88, cost: 82, effect: { type: 'evasion', duration: 1 } },
  IceBeam: { type: 'Water', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 50, effect: { type: 'freeze', chance: 0.25, duration: 3 } },
  Blizzard: { type: 'Water', damage: 36, warmup: 5, cooldown: 6, stamina: 65, cost: 80, effect: { type: 'freeze', chance: 0.4, duration: 4 } },
  LeafBlade: { type: 'Grass', damage: 27, warmup: 1, cooldown: 3, stamina: 38, cost: 45, effect: { type: 'high_crit' } },
  GigaDrain: { type: 'Grass', damage: 22, warmup: 3, cooldown: 4, stamina: 35, cost: 45, effect: { type: 'drain', chance: 0.5, duration: 1, healPercent: 0.25 } },
  PowerWhip: { type: 'Grass', damage: 32, warmup: 4, cooldown: 5, stamina: 50, cost: 65, effect: { type: 'flinch', chance: 0.3 } },
  FireFang: { type: 'Fire', damage: 20, warmup: 1, cooldown: 3, stamina: 30, cost: 40, effect: { type: 'burn', chance: 0.15, duration: 3, damage: 2 } },
  LavaPlume: { type: 'Fire', damage: 30, warmup: 4, cooldown: 5, stamina: 50, cost: 60, effect: { type: 'burn', chance: 0.35, duration: 4, damage: 3 } },
  VoltSwitch: { type: 'Electric', damage: 18, warmup: 1, cooldown: 2, stamina: 25, cost: 35, effect: { type: 'energize', chance: 0.3, duration: 2, staminaBoost: 3 } },
  WildCharge: { type: 'Electric', damage: 32, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'paralyze', chance: 0.25, duration: 4 } },
  Hypnosis: { type: 'Psychic', damage: 20, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'sleep', chance: 0.6, duration: 3 } },
  Psyshock: { type: 'Psychic', damage: 28, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'confuse', chance: 0.35, duration: 4 } },
  ZenHeadbutt: { type: 'Psychic', damage: 24, warmup: 2, cooldown: 4, stamina: 35, cost: 45, effect: { type: 'confuse', chance: 0.25, duration: 3 } },
  QuickAttack: { type: 'Normal', damage: 10, warmup: 0, cooldown: 2, stamina: 22, cost: 30, effect: { type: 'buff_speed', chance: 0.2, duration: 3 } },
  ExtremeSpeed: { type: 'Normal', damage: 19, warmup: 0, cooldown: 3, stamina: 38, cost: 52, effect: { type: 'always_hits' } },
  DoubleEdge: { type: 'Normal', damage: 34, warmup: 3, cooldown: 5, stamina: 58, cost: 68, effect: { type: 'recoil', damagePercent: 0.25 } },
  StoneEdge: { type: 'Normal', damage: 27, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'high_crit' } },
  PlayRough: { type: 'Normal', damage: 24, warmup: 2, cooldown: 4, stamina: 42, cost: 52, effect: { type: 'debuff_attack', chance: 0.2, duration: 4 } },
  DragonClaw: { type: 'Fighting', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'buff_attack', chance: 0.15, duration: 4 } },
  FlareBlitz: { type: 'Fire', damage: 36, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'recoil', damagePercent: 0.2 } },
  IronHead: { type: 'Normal', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'stun', chance: 0.3, duration: 2 } },
  RockSlide: { type: 'Fighting', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'stun', chance: 0.2, duration: 1 } },
  ShadowBall: { type: 'Psychic', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'debuff_defense', chance: 0.2, duration: 4 } },
  SludgeBomb: { type: 'Grass', damage: 30, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'poison', chance: 0.4, duration: 6, damage: 4 } },
  IronTail: { type: 'Normal', damage: 32, warmup: 3, cooldown: 4, stamina: 50, cost: 62, effect: { type: 'stun', chance: 0.25, duration: 2 } },
  SteelWing: { type: 'Normal', damage: 24, warmup: 1, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'buff_defense', chance: 0.1, duration: 4 } },
  AerialAce: { type: 'Normal', damage: 20, warmup: 0, cooldown: 2, stamina: 28, cost: 38, effect: { type: 'always_hits' } },
  DarkPulse: { type: 'Psychic', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'flinch', chance: 0.2 } },
  BlueFlare: { type: 'Fire', damage: 40, warmup: 6, cooldown: 7, stamina: 88, cost: 88, effect: { type: 'burn', chance: 0.5, duration: 4, damage: 3 } },
  DiamondStorm: { type: 'Fighting', damage: 33, warmup: 4, cooldown: 5, stamina: 55, cost: 68, effect: { type: 'buff_defense', chance: 0.5, duration: 6 } },
  PayDay: { type: 'Normal', damage: 15, warmup: 0, cooldown: 2, stamina: 25, cost: 35, effect: { type: 'energize', chance: 0.5, staminaBoost: 5 } },

  // Additional moves from support card hints
  AirSlash: { type: 'Normal', damage: 25, warmup: 2, cooldown: 3, stamina: 40, cost: 50, effect: { type: 'flinch', chance: 0.3 } },
  AncientPower: { type: 'Normal', damage: 20, warmup: 2, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'buff_all', chance: 0.1 } },
  AquaRing: { type: 'Water', damage: 0, warmup: 2, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'regen', duration: 5, healPercent: 0.06 } },
  Attract: { type: 'Normal', damage: 0, warmup: 1, cooldown: 5, stamina: 25, cost: 35, effect: { type: 'infatuate', chance: 0.5, duration: 3 } },
  BlastBurn: { type: 'Fire', damage: 42, warmup: 6, cooldown: 8, stamina: 68, cost: 85, effect: { type: 'exhaust', duration: 2 } },
  BraveBird: { type: 'Normal', damage: 36, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'recoil', damagePercent: 0.25 } },
  BulkUp: { type: 'Fighting', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_attack_defense', duration: 8 } },
  BulletPunch: { type: 'Fighting', damage: 16, warmup: 0, cooldown: 2, stamina: 28, cost: 38, effect: { type: 'flinch', chance: 0.15 } },
  CalmMind: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_instinct', duration: 8 } },
  Curse: { type: 'Psychic', damage: 0, warmup: 3, cooldown: 6, stamina: 40, cost: 50, effect: { type: 'curse', duration: 5, damage: 6 } },
  DazzlingGleam: { type: 'Normal', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'debuff_instinct', chance: 0.2, duration: 4 } },
  DestinyBond: { type: 'Psychic', damage: 0, warmup: 3, cooldown: 8, stamina: 50, cost: 60, effect: { type: 'destiny_bond', duration: 2 } },
  DracoMeteor: { type: 'Fire', damage: 40, warmup: 6, cooldown: 7, stamina: 65, cost: 82, effect: { type: 'debuff_instinct_self', duration: 2 } },
  DragonDance: { type: 'Fighting', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_attack_speed', duration: 8 } },
  DragonPulse: { type: 'Fire', damage: 29, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'debuff_instinct', chance: 0.15, duration: 3 } },
  DragonRush: { type: 'Fighting', damage: 32, warmup: 4, cooldown: 5, stamina: 52, cost: 65, effect: { type: 'stun', chance: 0.2, duration: 1 } },
  DragonTail: { type: 'Fighting', damage: 20, warmup: 2, cooldown: 4, stamina: 35, cost: 45, effect: { type: 'push_back' } },
  DreamEater: { type: 'Psychic', damage: 32, warmup: 4, cooldown: 5, stamina: 48, cost: 60, effect: { type: 'drain_sleep', healPercent: 0.5 } },
  EarthPower: { type: 'Fighting', damage: 30, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'debuff_defense', chance: 0.1, duration: 2 } },
  Eruption: { type: 'Fire', damage: 42, warmup: 6, cooldown: 7, stamina: 70, cost: 85, effect: { type: 'hp_based_damage' } },
  Explosion: { type: 'Normal', damage: 45, warmup: 5, cooldown: 10, stamina: 85, cost: 90, effect: { type: 'self_ko' } },
  FeintAttack: { type: 'Psychic', damage: 20, warmup: 1, cooldown: 2, stamina: 30, cost: 40, effect: { type: 'always_hits' } },
  FirePunch: { type: 'Fire', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'burn', chance: 0.2, duration: 3, damage: 2 } },
  FlashCannon: { type: 'Normal', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'debuff_defense', chance: 0.1, duration: 8 } },
  FocusBlast: { type: 'Fighting', damage: 36, warmup: 5, cooldown: 6, stamina: 58, cost: 72, effect: { type: 'debuff_defense', chance: 0.1, duration: 12 } },
  FoulPlay: { type: 'Psychic', damage: 30, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'use_opponent_attack' } },
  FusionFlare: { type: 'Fire', damage: 38, warmup: 6, cooldown: 6, stamina: 62, cost: 78, effect: { type: 'burn', chance: 0.3, duration: 4, damage: 3 } },
  FutureSight: { type: 'Psychic', damage: 36, warmup: 5, cooldown: 7, stamina: 55, cost: 70, effect: { type: 'delayed_damage', turns: 3 } },
  HeatWave: { type: 'Fire', damage: 31, warmup: 4, cooldown: 5, stamina: 50, cost: 62, effect: { type: 'burn', chance: 0.2, duration: 3, damage: 2 } },
  Hex: { type: 'Psychic', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'double_if_status' } },
  Hurricane: { type: 'Normal', damage: 36, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'confuse', chance: 0.3, duration: 3 } },
  IcePunch: { type: 'Water', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'freeze', chance: 0.2, duration: 3 } },
  IronDefense: { type: 'Normal', damage: 0, warmup: 2, cooldown: 5, stamina: 35, cost: 45, effect: { type: 'buff_defense', duration: 12 } },
  MeteorMash: { type: 'Normal', damage: 30, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'buff_attack', chance: 0.2, duration: 8 } },
  Metronome: { type: 'Normal', damage: 0, warmup: 2, cooldown: 5, stamina: 35, cost: 45, effect: { type: 'random_move' } },
  MilkDrink: { type: 'Normal', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'heal_self', healPercent: 0.35 } },
  Moonblast: { type: 'Normal', damage: 31, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'debuff_instinct', chance: 0.3, duration: 8 } },
  Moonlight: { type: 'Normal', damage: 0, warmup: 3, cooldown: 6, stamina: 40, cost: 50, effect: { type: 'heal_self', healPercent: 0.6 } },
  NastyPlot: { type: 'Psychic', damage: 0, warmup: 2, cooldown: 5, stamina: 35, cost: 48, effect: { type: 'buff_instinct', duration: 12 } },
  Outrage: { type: 'Fighting', damage: 36, warmup: 4, cooldown: 6, stamina: 58, cost: 72, effect: { type: 'confuse_self_after', duration: 2 } },
  PowerGem: { type: 'Normal', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'high_crit' } },
  Present: { type: 'Normal', damage: 20, warmup: 1, cooldown: 3, stamina: 30, cost: 40, effect: { type: 'random_damage_or_heal' } },
  RapidSpin: { type: 'Normal', damage: 15, warmup: 1, cooldown: 2, stamina: 25, cost: 35, effect: { type: 'remove_hazards' } },
  Recover: { type: 'Normal', damage: 0, warmup: 2, cooldown: 5, stamina: 35, cost: 45, effect: { type: 'heal_self', healPercent: 0.5 } },
  RockPolish: { type: 'Fighting', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_speed', duration: 8 } },
  Rollout: { type: 'Normal', damage: 12, warmup: 1, cooldown: 2, stamina: 25, cost: 35, effect: { type: 'consecutive_boost', maxHits: 5 } },
  Roost: { type: 'Normal', damage: 0, warmup: 1, cooldown: 6, stamina: 25, cost: 38, effect: { type: 'heal_self', healPercent: 0.4 } },
  Sandstorm: { type: 'Fighting', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 45, effect: { type: 'weather_sand' } },
  Screech: { type: 'Normal', damage: 0, warmup: 0, cooldown: 3, stamina: 25, cost: 35, effect: { type: 'debuff_defense', duration: 6 } },
  Slash: { type: 'Normal', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'high_crit' } },
  SleepPowder: { type: 'Grass', damage: 0, warmup: 2, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'sleep', chance: 0.75, duration: 3 } },
  SludgeWave: { type: 'Grass', damage: 31, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'poison', chance: 0.3, duration: 6, damage: 4 } },
  Spikes: { type: 'Normal', damage: 0, warmup: 2, cooldown: 6, stamina: 30, cost: 40, effect: { type: 'entry_hazard', layers: 3 } },
  StealthRock: { type: 'Fighting', damage: 0, warmup: 2, cooldown: 6, stamina: 30, cost: 40, effect: { type: 'entry_hazard_rock' } },
  SwordsDance: { type: 'Fighting', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_attack', duration: 8 } },
  Synthesis: { type: 'Grass', damage: 0, warmup: 2, cooldown: 4, stamina: 30, cost: 42, effect: { type: 'heal_self', healPercent: 0.45 } },
  ThunderWave: { type: 'Electric', damage: 0, warmup: 1, cooldown: 4, stamina: 25, cost: 35, effect: { type: 'paralyze', chance: 0.9, duration: 5 } },
  Toxic: { type: 'Grass', damage: 0, warmup: 2, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'badly_poison', duration: 6 } },
  Transform: { type: 'Normal', damage: 0, warmup: 3, cooldown: 10, stamina: 40, cost: 50, effect: { type: 'copy_opponent' } },
  UTurn: { type: 'Normal', damage: 21, warmup: 1, cooldown: 3, stamina: 32, cost: 42, effect: { type: 'switch_out' } },
  Waterfall: { type: 'Water', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'stun', chance: 0.2, duration: 1 } },
  WillOWisp: { type: 'Fire', damage: 0, warmup: 2, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'burn', chance: 0.85, duration: 4, damage: 4 } },

  // === CHIPPER MOVES (Low stamina, low cooldown for each type) ===
  FlameCharge: { type: 'Fire', damage: 12, warmup: 0, cooldown: 3, stamina: 18, cost: 28, effect: { type: 'buff_speed', chance: 1.0, duration: 6 } },
  Incinerate: { type: 'Fire', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'burn', chance: 0.1, duration: 2, damage: 1 } },
  AquaJet: { type: 'Water', damage: 14, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'buff_speed', chance: 0.15, duration: 3 } },
  BubbleBeam: { type: 'Water', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'debuff_speed', chance: 0.1, duration: 4 } },
  BulletSeed: { type: 'Grass', damage: 15, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'consecutive_boost', maxHits: 5 } },
  MegaDrain: { type: 'Grass', damage: 14, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'drain', chance: 0.3, healPercent: 0.25 } },
  Spark: { type: 'Electric', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'paralyze', chance: 0.15, duration: 2 } },
  ChargeBeam: { type: 'Electric', damage: 12, warmup: 0, cooldown: 3, stamina: 18, cost: 28, effect: { type: 'buff_instinct', chance: 0.7, duration: 6 } },
  Confusion: { type: 'Psychic', damage: 14, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'confuse', chance: 0.1, duration: 2 } },
  HeartStamp: { type: 'Psychic', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'stun', chance: 0.15, duration: 1 } },
  MachPunch: { type: 'Fighting', damage: 14, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'buff_attack', chance: 0.1, duration: 4 } },
  ForcePalm: { type: 'Fighting', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'paralyze', chance: 0.2, duration: 2 } },
  Bite: { type: 'Normal', damage: 15, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'stun', chance: 0.15, duration: 1 } },
  Swift: { type: 'Normal', damage: 16, warmup: 0, cooldown: 2, stamina: 20, cost: 30, effect: { type: 'always_hits' } },

  // === BUFF MOVES (For Scaler strategy - each with distinct trade-offs) ===
  Agility: { type: 'Psychic', damage: 0, warmup: 0, cooldown: 3, stamina: 20, cost: 32, effect: { type: 'buff_speed', duration: 10 } },
  Harden: { type: 'Normal', damage: 0, warmup: 0, cooldown: 3, stamina: 15, cost: 25, effect: { type: 'buff_defense', duration: 5 } },
  Meditate: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 5, stamina: 30, cost: 42, effect: { type: 'buff_attack', duration: 12 } },
  Sharpen: { type: 'Normal', damage: 0, warmup: 0, cooldown: 2, stamina: 12, cost: 22, effect: { type: 'buff_attack', duration: 4 } },
  WorkUp: { type: 'Normal', damage: 0, warmup: 0, cooldown: 4, stamina: 22, cost: 35, effect: { type: 'buff_attack_defense', duration: 6 } },
  CosmicPower: { type: 'Psychic', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 48, effect: { type: 'buff_defense', duration: 14 } },
  Barrier: { type: 'Psychic', damage: 0, warmup: 0, cooldown: 4, stamina: 22, cost: 32, effect: { type: 'buff_defense', duration: 8 } },
  Amnesia: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 5, stamina: 28, cost: 40, effect: { type: 'buff_instinct', duration: 10 } },

  // === DEBUFF MOVES (For Debuffer strategy - varied costs/durations) ===
  Growl: { type: 'Normal', damage: 0, warmup: 0, cooldown: 2, stamina: 12, cost: 22, effect: { type: 'debuff_attack', duration: 5 } },
  Leer: { type: 'Normal', damage: 0, warmup: 0, cooldown: 2, stamina: 12, cost: 22, effect: { type: 'debuff_defense', duration: 5 } },
  TailWhip: { type: 'Normal', damage: 0, warmup: 0, cooldown: 3, stamina: 18, cost: 28, effect: { type: 'debuff_defense', duration: 8 } },
  SandAttack: { type: 'Fighting', damage: 0, warmup: 0, cooldown: 3, stamina: 15, cost: 25, effect: { type: 'debuff_accuracy', duration: 6 } },
  Confide: { type: 'Normal', damage: 0, warmup: 0, cooldown: 3, stamina: 15, cost: 25, effect: { type: 'debuff_instinct', duration: 6 } },
  CharmMove: { type: 'Normal', damage: 0, warmup: 1, cooldown: 4, stamina: 22, cost: 35, effect: { type: 'debuff_attack', duration: 10 } },
  FakeTears: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 4, stamina: 22, cost: 35, effect: { type: 'debuff_defense', duration: 10 } },
  ScaryFace: { type: 'Normal', damage: 0, warmup: 0, cooldown: 3, stamina: 18, cost: 28, effect: { type: 'debuff_speed', duration: 8 } },
  StringShot: { type: 'Grass', damage: 0, warmup: 0, cooldown: 2, stamina: 12, cost: 22, effect: { type: 'debuff_speed', duration: 5 } },
  Smokescreen: { type: 'Fire', damage: 0, warmup: 0, cooldown: 3, stamina: 15, cost: 25, effect: { type: 'debuff_accuracy', duration: 7 } },

  // === WEATHER MOVES (persist until replaced by another weather move) ===
  RainDance: { type: 'Water', damage: 0, warmup: 1, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'weather_rain' } },
  SunnyDay: { type: 'Fire', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 45, effect: { type: 'weather_sun' } },
  Hail: { type: 'Water', damage: 0, warmup: 3, cooldown: 7, stamina: 40, cost: 50, effect: { type: 'weather_hail' } },

  // === NEW MID-TIER DAMAGE MOVES ===
  FlameBurst: { type: 'Fire', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'burn', chance: 0.15, duration: 2, damage: 2 } },
  Overheat: { type: 'Fire', damage: 38, warmup: 5, cooldown: 6, stamina: 62, cost: 78, effect: { type: 'debuff_instinct_self', duration: 12 } },
  Scald: { type: 'Water', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 45, effect: { type: 'burn', chance: 0.3, duration: 3, damage: 2 } },
  AquaTail: { type: 'Water', damage: 30, warmup: 3, cooldown: 4, stamina: 48, cost: 55, effect: { type: 'flinch', chance: 0.2 } },
  Brine: { type: 'Water', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'double_if_half_hp' } },
  SeedBomb: { type: 'Grass', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 50, effect: { type: 'debuff_speed', chance: 0.15, duration: 3 } },
  EnergyBall: { type: 'Grass', damage: 30, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'debuff_defense', chance: 0.1, duration: 8 } },
  WoodHammer: { type: 'Grass', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'recoil', damagePercent: 0.2 } },
  Discharge: { type: 'Electric', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 50, effect: { type: 'paralyze', chance: 0.25, duration: 3 } },
  ElectroBall: { type: 'Electric', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'buff_speed', chance: 0.2, duration: 4 } },
  ZapCannon: { type: 'Electric', damage: 36, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'paralyze', chance: 0.6, duration: 4 } },
  Extrasensory: { type: 'Psychic', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'stun', chance: 0.15, duration: 1 } },
  PsychoCut: { type: 'Psychic', damage: 24, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'high_crit' } },
  StoredPower: { type: 'Psychic', damage: 20, warmup: 2, cooldown: 3, stamina: 32, cost: 40, effect: { type: 'buff_boost_damage' } },
  CrossChop: { type: 'Fighting', damage: 32, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'high_crit' } },
  HammerArm: { type: 'Fighting', damage: 34, warmup: 4, cooldown: 5, stamina: 52, cost: 65, effect: { type: 'debuff_speed_self', duration: 10 } },
  Superpower: { type: 'Fighting', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'debuff_attack_self', duration: 10 } },
  VacuumWave: { type: 'Fighting', damage: 14, warmup: 0, cooldown: 2, stamina: 18, cost: 28, effect: { type: 'debuff_defense', chance: 0.1, duration: 3 } },
  Headbutt: { type: 'Normal', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'stun', chance: 0.2, duration: 1 } },
  Facade: { type: 'Normal', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 45, effect: { type: 'double_if_status_self' } },
  Frustration: { type: 'Normal', damage: 28, warmup: 1, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'debuff_speed_self', duration: 3 } },
  Return: { type: 'Normal', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 45, effect: { type: 'buff_speed', chance: 0.3, duration: 4 } },
  GigaImpact: { type: 'Normal', damage: 42, warmup: 7, cooldown: 8, stamina: 70, cost: 85, effect: { type: 'exhaust', duration: 2 } },

  // === SIGNATURE/UNIQUE MOVES ===
  SkyAttack: { type: 'Normal', damage: 36, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'high_crit' } },
  MindBlown: { type: 'Fire', damage: 40, warmup: 5, cooldown: 6, stamina: 65, cost: 80, effect: { type: 'recoil', damagePercent: 0.25 } },
  SheerCold: { type: 'Water', damage: 45, warmup: 6, cooldown: 8, stamina: 75, cost: 88, effect: { type: 'freeze', chance: 0.5, duration: 4 } },
  Frenzy: { type: 'Grass', damage: 42, warmup: 6, cooldown: 8, stamina: 70, cost: 85, effect: { type: 'exhaust', duration: 2 } },
  Focus: { type: 'Fighting', damage: 0, warmup: 2, cooldown: 5, stamina: 25, cost: 35, effect: { type: 'buff_instinct', duration: 10 } },
  PsychicTerrain: { type: 'Psychic', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 45, effect: { type: 'terrain_psychic' } },
  ElectricTerrain: { type: 'Electric', damage: 0, warmup: 1, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'terrain_electric' } },
  GrassyTerrain: { type: 'Grass', damage: 0, warmup: 3, cooldown: 7, stamina: 40, cost: 50, effect: { type: 'terrain_grassy' } },

  // === SUPPORT CARD HINT MOVES (Gen 8-9) ===
  // Zacian/Zamazenta signature moves
  BehemothBlade: { type: 'Normal', damage: 38, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'high_crit' } },
  BehemothBash: { type: 'Normal', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'buff_defense', chance: 0.4, duration: 8 } },
  SacredSword: { type: 'Fighting', damage: 30, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'ignore_defense' } },

  // Eternatus signature move
  DynamaxCannon: { type: 'Psychic', damage: 38, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'debuff_defense', chance: 0.3, duration: 4 } },

  // Terapagos signature move
  TeraStarstorm: { type: 'Normal', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'buff_all', chance: 0.2 } },

  // Ogerpon signature move
  IvyCudgel: { type: 'Grass', damage: 30, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'high_crit' } },

  // Duraludon signature move
  SteelBeam: { type: 'Normal', damage: 38, warmup: 5, cooldown: 6, stamina: 60, cost: 75, effect: { type: 'recoil', damagePercent: 0.25 } },

  // Drednaw moves
  Liquidation: { type: 'Water', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'debuff_defense', chance: 0.2, duration: 6 } },
  RockTomb: { type: 'Fighting', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'debuff_speed', chance: 0.5, duration: 6 } },
  JawLock: { type: 'Psychic', damage: 24, warmup: 2, cooldown: 4, stamina: 40, cost: 48, effect: { type: 'debuff_speed', chance: 0.5, duration: 4 } },
  ShellSmash: { type: 'Normal', damage: 0, warmup: 2, cooldown: 6, stamina: 40, cost: 52, effect: { type: 'buff_attack_speed', duration: 14 } },
  HeadSmash: { type: 'Fighting', damage: 40, warmup: 5, cooldown: 6, stamina: 65, cost: 80, effect: { type: 'recoil', damagePercent: 0.3 } },

  // Toxtricity signature move
  Overdrive: { type: 'Electric', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'paralyze', chance: 0.15, duration: 2 } },
  BoomBurst: { type: 'Normal', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 70, effect: { type: 'debuff_defense', chance: 0.2, duration: 3 } },
  ShiftGear: { type: 'Normal', damage: 0, warmup: 0, cooldown: 4, stamina: 25, cost: 35, effect: { type: 'buff_speed', duration: 10 } },

  // Tinkaton signature move
  GigatonHammer: { type: 'Normal', damage: 42, warmup: 5, cooldown: 7, stamina: 68, cost: 85, effect: { type: 'stun', chance: 0.4, duration: 2 } },

  // Additional missing moves from Pokemon moveHints
  CrossPoison: { type: 'Grass', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 45, effect: { type: 'poison', chance: 0.2, duration: 6, damage: 3 } },
  HornLeech: { type: 'Grass', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'drain', chance: 0.5, healPercent: 0.25 } },
  BodyPress: { type: 'Fighting', damage: 28, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'defense_as_attack' } },
  Crunch: { type: 'Psychic', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'debuff_defense', chance: 0.2, duration: 6 } },

  // Missing moves from support card moveHints
  Charm: { type: 'Normal', damage: 0, warmup: 1, cooldown: 4, stamina: 25, cost: 35, effect: { type: 'debuff_attack', duration: 6 } },
  Coil: { type: 'Grass', damage: 0, warmup: 1, cooldown: 4, stamina: 30, cost: 40, effect: { type: 'buff_attack_defense', duration: 8 } },
  CollisionCourse: { type: 'Fighting', damage: 38, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'recoil', damagePercent: 0.1 } },
  CottonGuard: { type: 'Grass', damage: 0, warmup: 2, cooldown: 6, stamina: 38, cost: 50, effect: { type: 'buff_defense', duration: 15 } },
  DrainingKiss: { type: 'Normal', damage: 18, warmup: 1, cooldown: 3, stamina: 30, cost: 38, effect: { type: 'drain', chance: 0.75, healPercent: 0.5 } },
  ElectroDrift: { type: 'Electric', damage: 35, warmup: 4, cooldown: 5, stamina: 55, cost: 68, effect: { type: 'buff_speed', chance: 0.3, duration: 4 } },
  Encore: { type: 'Normal', damage: 0, warmup: 1, cooldown: 5, stamina: 25, cost: 35, effect: { type: 'debuff_instinct', duration: 6 } },
  FireLash: { type: 'Fire', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'debuff_defense', chance: 1.0, duration: 6 } },
  FreezeDry: { type: 'Water', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'freeze', chance: 0.1, duration: 3 } },
  GMaxWildfire: { type: 'Fire', damage: 42, warmup: 6, cooldown: 7, stamina: 75, cost: 90, effect: { type: 'burn', chance: 0.5, duration: 6, damage: 5 } },
  HeatCrash: { type: 'Fire', damage: 30, warmup: 2, cooldown: 3, stamina: 45, cost: 55, effect: { type: 'stun', chance: 0.2, duration: 1 } },
  HighHorsepower: { type: 'Fire', damage: 32, warmup: 3, cooldown: 4, stamina: 50, cost: 60, effect: { type: 'debuff_speed', chance: 0.2, duration: 3 } },
  HyperVoice: { type: 'Normal', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'confuse', chance: 0.15, duration: 2 } },
  KnockOff: { type: 'Psychic', damage: 22, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'debuff_attack', chance: 0.3, duration: 4 } },
  KowtowCleave: { type: 'Psychic', damage: 32, warmup: 3, cooldown: 4, stamina: 48, cost: 60, effect: { type: 'high_crit' } },
  LeechSeed: { type: 'Grass', damage: 8, warmup: 2, cooldown: 5, stamina: 30, cost: 40, effect: { type: 'drain', chance: 1.0, healPercent: 0.5 } },
  LightScreen: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 6, stamina: 28, cost: 38, effect: { type: 'buff_instinct', duration: 6 } },
  Megahorn: { type: 'Grass', damage: 36, warmup: 4, cooldown: 5, stamina: 55, cost: 68, effect: { type: 'high_crit' } },
  MistyTerrain: { type: 'Normal', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 45, effect: { type: 'terrain_misty' } },
  MoongeistBeam: { type: 'Psychic', damage: 38, warmup: 5, cooldown: 6, stamina: 62, cost: 78, effect: { type: 'debuff_instinct', chance: 0.4, duration: 4 } },
  Nuzzle: { type: 'Electric', damage: 12, warmup: 0, cooldown: 2, stamina: 20, cost: 28, effect: { type: 'paralyze', chance: 1.0, duration: 4 } },
  PoisonJab: { type: 'Grass', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 48, effect: { type: 'poison', chance: 0.3, duration: 6, damage: 3 } },
  PollenPuff: { type: 'Grass', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'heal_self', healPercent: 0.15 } },
  Psychicfangs: { type: 'Psychic', damage: 28, warmup: 2, cooldown: 3, stamina: 42, cost: 52, effect: { type: 'debuff_defense', chance: 0.3, duration: 3 } },
  Reflect: { type: 'Psychic', damage: 0, warmup: 1, cooldown: 5, stamina: 25, cost: 35, effect: { type: 'buff_defense', duration: 5 } },
  Rest: { type: 'Normal', damage: 0, warmup: 2, cooldown: 8, stamina: 40, cost: 50, effect: { type: 'heal_self', healPercent: 1.0 } },
  Reversal: { type: 'Fighting', damage: 20, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'low_hp_boost' } },
  ShellSideArm: { type: 'Grass', damage: 30, warmup: 3, cooldown: 4, stamina: 45, cost: 55, effect: { type: 'poison', chance: 0.2, duration: 6, damage: 3 } },
  Sing: { type: 'Normal', damage: 0, warmup: 1, cooldown: 5, stamina: 25, cost: 35, effect: { type: 'sleep', chance: 0.55, duration: 3 } },
  SlackOff: { type: 'Normal', damage: 0, warmup: 3, cooldown: 7, stamina: 45, cost: 55, effect: { type: 'heal_self', healPercent: 0.65 } },
  SpiritBreak: { type: 'Normal', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 50, effect: { type: 'debuff_attack', chance: 1.0, duration: 6 } },
  Stomp: { type: 'Normal', damage: 22, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'flinch', chance: 0.3 } },
  SuckerPunch: { type: 'Psychic', damage: 24, warmup: 0, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'stun', chance: 0.15, duration: 1 } },
  SurgingStrikes: { type: 'Water', damage: 30, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'always_crit' } },
  TarShot: { type: 'Fire', damage: 0, warmup: 1, cooldown: 4, stamina: 25, cost: 35, effect: { type: 'debuff_speed', duration: 8 } },
  Taunt: { type: 'Psychic', damage: 0, warmup: 0, cooldown: 3, stamina: 20, cost: 30, effect: { type: 'debuff_instinct', duration: 6 } },
  Uturn: { type: 'Grass', damage: 22, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'switch_out' } },
  WickedBlow: { type: 'Psychic', damage: 35, warmup: 4, cooldown: 5, stamina: 55, cost: 68, effect: { type: 'always_crit' } },
  Wish: { type: 'Normal', damage: 0, warmup: 2, cooldown: 6, stamina: 35, cost: 45, effect: { type: 'delayed_heal', healPercent: 0.5 } },

  // === ADDITIONAL WATER MOVES (for better type distribution) ===
  AquaCutter: { type: 'Water', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'high_crit' } },
  RazorShell: { type: 'Water', damage: 26, warmup: 2, cooldown: 3, stamina: 40, cost: 50, effect: { type: 'debuff_defense', chance: 0.5, duration: 6 } },
  FlipTurn: { type: 'Water', damage: 20, warmup: 1, cooldown: 3, stamina: 32, cost: 42, effect: { type: 'switch_out' } },
  WaterPulse: { type: 'Water', damage: 20, warmup: 1, cooldown: 3, stamina: 32, cost: 40, effect: { type: 'confuse', chance: 0.2, duration: 2 } },
  Whirlpool: { type: 'Water', damage: 18, warmup: 1, cooldown: 3, stamina: 30, cost: 38, effect: { type: 'debuff_speed', chance: 0.4, duration: 4 } },
  WaveCrash: { type: 'Water', damage: 36, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'recoil', damagePercent: 0.2 } },
  TripleAxel: { type: 'Water', damage: 32, warmup: 3, cooldown: 4, stamina: 48, cost: 58, effect: { type: 'consecutive_boost', maxHits: 3 } },
  AuroraBeam: { type: 'Water', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'debuff_attack', chance: 0.1, duration: 8 } },
  Dive: { type: 'Water', damage: 28, warmup: 3, cooldown: 4, stamina: 42, cost: 52, effect: { type: 'evasion', duration: 1 } },
  LifeDew: { type: 'Water', damage: 0, warmup: 2, cooldown: 5, stamina: 35, cost: 45, effect: { type: 'heal_self', healPercent: 0.25 } },

  // === ADDITIONAL ELECTRIC MOVES (for better type distribution) ===
  VoltTackle: { type: 'Electric', damage: 36, warmup: 4, cooldown: 5, stamina: 58, cost: 72, effect: { type: 'recoil', damagePercent: 0.25 } },
  ThunderFang: { type: 'Electric', damage: 22, warmup: 1, cooldown: 3, stamina: 35, cost: 42, effect: { type: 'paralyze', chance: 0.2, duration: 3 } },
  ParabolicCharge: { type: 'Electric', damage: 22, warmup: 2, cooldown: 3, stamina: 35, cost: 45, effect: { type: 'drain', chance: 0.5, healPercent: 0.25 } },
  RisingVoltage: { type: 'Electric', damage: 24, warmup: 2, cooldown: 3, stamina: 38, cost: 48, effect: { type: 'buff_instinct', chance: 0.25, duration: 4 } },
  Electroweb: { type: 'Electric', damage: 18, warmup: 1, cooldown: 3, stamina: 30, cost: 38, effect: { type: 'debuff_speed', chance: 1.0, duration: 4 } },
  ShockWave: { type: 'Electric', damage: 20, warmup: 0, cooldown: 2, stamina: 28, cost: 35, effect: { type: 'always_hits' } },
  ZingZap: { type: 'Electric', damage: 28, warmup: 2, cooldown: 4, stamina: 42, cost: 52, effect: { type: 'stun', chance: 0.3, duration: 1 } },
  BoltBeak: { type: 'Electric', damage: 32, warmup: 2, cooldown: 3, stamina: 45, cost: 55, effect: { type: 'double_if_half_hp' } },
  PlasmaFists: { type: 'Electric', damage: 34, warmup: 3, cooldown: 4, stamina: 52, cost: 62, effect: { type: 'drain', chance: 0.3, healPercent: 0.2 } },
  SupremeVoltage: { type: 'Electric', damage: 40, warmup: 5, cooldown: 6, stamina: 65, cost: 80, effect: { type: 'paralyze', chance: 0.4, duration: 5 } }
};

